# Generated by Django 6.0.2 on 2026-02-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
